### PR TITLE
Fix Windows 10 support.

### LINKED ISSUE #13: uname_os_check 'MSYS_NT-10.0' got converted to 'msys_nt-10.0' which is not a GOOS value
It is the same issue as #3 which is not really fixed. 519ed576b3ed9ccd6ba014e3774b6704bbb84481 added `msys_nt`, but not `msys_nt-10.0`.

### PR DESCRIPTION
**Pull request by AlekSi**
Closes #13.

### CODE REVIEW

**Comment by AlekSi** [comment]
Travis CI failed for an unrelated reason, PTAL.

**Comment by syntaqx** [comment]
Excited to see this get merged.

**Comment by syntaqx** [comment]
```sh
uname_os() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    msys_nt*) os="windows" ;;
    mingw*) os="windows" ;;
  esac
  echo "$os"
}
```

You'll probably want something like this to be more friendly with `git-bash.exe`, which is the more common shell installation most people use (not the best, just most common)

> __Note:__ I have basically no practical knowledge of shell scripting, so I'm sure there's a more optimized way to write that - Functionally was all I was referring to.

**Comment by codyaray** [comment]
+1 also just ran into this issue.

+1 for `mingw*` as well.

Please merge! :)

**Comment by DABH** [comment]
+1 for @syntaqx 's solution cc @client9 -- thanks for taking the time to fix this!  (confirmed the fix works on win10 + git bash)

**Comment by AlekSi** [comment]
Updated PR with @syntaqx's solution.

@client9 Please find a minute to click merge button – it is a small change, it is tested by us, and fixes a real problem we are having.

**Comment by AlekSi** [comment]
Thank you!

**Comment by client9** [comment]
@AlekSi and friends... I'd be happy to give you commit writes if you want!  Windows is something I'm never going to be able to support!

**Comment by syntaqx** [comment]
@client9 If you need help with Windows support I'm happy to help. I work on Windows full time and fix this kind of stuff constantly :P

**Comment by client9** [comment]
and it was so  💥 

thanks @syntaqx

**Comment by DABH** [comment]
Same here, my company is now relying on this package so have a vested interest in keeping it working smoothly on all platforms :)  Would be happy to help maintain.  Thanks again for the fast reply and for merging! 💯

**Comment by client9** [comment]
I'd love to know how you all are using it. @syntaqx @DABH  !

**Comment by DABH** [comment]
In my case we have a cross-platform installer script for a software package, which users can `curl ... | sh` to download and install on their machines.  So one can imagine how many of these scripts are useful :)

**Comment by syntaqx** [comment]
My first use case was when I was using https://goreleaser.com/ to automate binary releases for a Go project. They had the project as a dependency.

Now I use it for pretty much any scripting suite I deliver. I work in operations/devops/infrastructure so scripts and their compatibility is life.

**Comment by codyaray** [comment]
@syntaqx same here. @DABH and I discovered this via godownloader as well. Pretty nice suite. :)

**Pull request merged**
